Repository kaburiba/RandomOkasi-, pull requests merged in 2023-02, with the labels that each got.

#3 [Add] .gitignoreファイルの追加
  .gitignore
Labels: 完成したよ, レビュー待ち

#10 [Add]テンプレートファイルの作成
  css/style.css
  img/Assorted.png
  img/account.svg
  img/logo.svg
  inc/head.php
  inc/header.php
  index.php
  toppage.php
Labels: 完成したよ

#13 [Update] テンプレートの適用とスタイル調整
  css/login.css
  css/style.css
  login.php
  top.php
Labels: 完成したよ

#15 [Update]db_connectの更新
  function/db_connect.php
Labels: 完成したよ, レビュー待ち

#20 [Update]一覧ページのバックエンドの更新
  infomation.php
Labels: レビュー待ち

#12 [Add]一覧ページのバックエンド
  css/common.css
  list.php
Labels: レビュー待ち

#16 [ADD]ユーザー情報編集の作成
  css/edit.css
  css/toppage.css
  edit.php
  login-page.php
  toppage.php
Labels: レビュー待ち

#11 APIから情報をとってくるjsの作成
  css/itiran.css
  css/random.css
  css/random_result.css
  function/getJsonData.php
  function/getRandomSnack.php
  function/getSearchSnacks.php
  itiran.php
  js/getAllSnacks.js
  js/getRandomSnacks.js
  js/getSearchSnack.js
  random.php
  random_result.php
Labels: 作業中
